#! /bin/bash

if ! command -v unzip &> /dev/null
then
    echo "'unzip' is required and could not be found.  Please install 'unzip'."
    exit
fi
if [[ -d "aws" ]] 
then
    rm -rf aws
fi
if [[ -f "awscliv2.zip" ]]
then
    rm -f awscliv2.zip
fi
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install --update
rm -rf aws
rm -f awscliv2.zip